/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import java.util.Scanner

fun main() {
    val interfas = InterfazCLI()
    val scanner = Scanner(System.`in`)
    var opcion: Int

    do {
        interfas.mostrarMenu()

        opcion = scanner.nextInt()

        when (opcion) {
            1 -> interfas.crearproyecto()
            2 -> interfas.crearusuario()
            3 -> interfas.creartarea()
            4 -> interfas.agregartareaaproyecto()
            5 -> interfas.agregarusuarioatarea()
            6 -> interfas.buscartareaporusuario()
            7 -> interfas.mostrarlosproyecto()
            0 -> println("¡Hasta luego!")
            else -> println("Opción inválida. Intente de nuevo.")
        }

        if (opcion != 0) {
            println("\nPresione Enter para continuar...")
            scanner.nextLine() // Limpiar buffer
            scanner.nextLine() // Esperar Enter
        }
    } while (opcion != 0)

    scanner.close()
}